apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: myblog.com
      http:
        paths:
          - path: /posts
            backend:
              serviceName: query-srv
              servicePort: 4002
          - path: /create_post
            backend:
              serviceName: posts-srv
              servicePort: 4000
          - path: /create_comment
            backend:
              serviceName: comments-srv
              servicePort: 4001
